# Generated by Django 3.2.7 on 2021-11-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choices',
        ),
    ]
