# Generated by Django 3.2.7 on 2021-11-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_poll_app', '0003_rename_question_text_question_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
