# Generated by Django 3.2.7 on 2021-11-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_poll_app', '0004_rename_question_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ice_cream_poll_app.questions'),
        ),
    ]
