# Generated by Django 3.2.7 on 2021-11-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_poll_app', '0006_auto_20211109_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='percentage_votes',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='total_votes',
        ),
    ]
