# Generated by Django 3.2.7 on 2021-11-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_poll_app', '0008_choices_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='percentage',
        ),
    ]
